('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('truy cập ổ D', {'entities': [(9, 12, 'PATH')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('mở file Báo cáo.docx trong ổ D', {'entities': [(8, 20, 'FILE'), (27, 30, 'PATH')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập D:\\Báo cáo', {'entities': [(9, 19, 'PATH')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('phát bài hát Hello trên PowerPoint', {'entities': [(13, 18, 'QUERY'), (24, 34, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('mở ứng dụng Spotify', {'entities': [(12, 19, 'APP')]}),
('mở file Hello.mp3', {'entities': [(8, 17, 'FILE')]}),
('mở file update.xlsx bằng Excel', {'entities': [(8, 19, 'FILE'), (25, 30, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở file update.xlsx', {'entities': [(8, 19, 'FILE')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Despacito trên Notepad', {'entities': [(13, 22, 'QUERY'), (28, 35, 'APP')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở ứng dụng Excel', {'entities': [(12, 17, 'APP')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('tìm video Hello trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP'), (40, 43, 'APP')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Hạ Còn Vương Nắng trên VLC', {'entities': [(13, 30, 'QUERY'), (36, 39, 'APP')]}),
('mở ứng dụng Word', {'entities': [(12, 16, 'APP')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file data.png', {'entities': [(8, 16, 'FILE')]}),
('mở ứng dụng Zalo', {'entities': [(12, 16, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở ứng dụng Notepad', {'entities': [(12, 19, 'APP')]}),
('phát bài hát Tháng Tư là lời nói dối trên Excel', {'entities': [(13, 36, 'QUERY'), (42, 47, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('mở ứng dụng Photoshop', {'entities': [(12, 21, 'APP')]}),
('mở ứng dụng Chrome', {'entities': [(12, 18, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở file Faded.mp4', {'entities': [(8, 17, 'FILE')]}),
('mở file report_final.pdf', {'entities': [(8, 24, 'FILE')]}),
('tìm file report_final.pdf trong thư mục Downloads', {'entities': [(9, 25, 'FILE'), (32, 49, 'PATH')]}),
('truy cập thư mục Tài liệu', {'entities': [(9, 25, 'PATH')]}),
('phát bài hát Yesterday trên Word', {'entities': [(13, 22, 'QUERY'), (28, 32, 'APP')]}),
('xem video Faded trên Youtube', {'entities': [(10, 15, 'QUERY'), (21, 28, 'APP')]}),
('mở file presentation.pptx', {'entities': [(8, 25, 'FILE')]}),
('mở ứng dụng VLC', {'entities': [(12, 15, 'APP')]}),
('truy cập thư mục Downloads', {'entities': [(9, 26, 'PATH')]}),
('mở file báo cáo.docx', {'entities': [(8, 20, 'FILE')]}),
('truy cập thư mục Học tập', {'entities': [(9, 24, 'PATH')]}),
('truy cập E:\\Media', {'entities': [(9, 17, 'PATH')]}),
('phát bài hát Faded trên Spotify', {'entities': [(13, 18, 'QUERY'), (24, 31, 'APP')]}),
('mở ứng dụng PowerPoint', {'entities': [(12, 22, 'APP')]}),
('truy cập C:\\Users\\Admin\\Documents', {'entities': [(9, 33, 'PATH')]}),
