TRAIN_DATA = [
('khởi chạy notepad', 'open_app'),
('vào paint đi', 'open_app'),
('hãy mở notepad', 'open_app'),
('tìm kiếm tài liệu hợp đồng lao động', 'find_file'),
('mở powerpoint', 'open_app'),
('ngưng chạy vscode', 'close_app'),
('đóng ứng dụng zalo', 'close_app'),
('kết thúc teams', 'close_app'),
('cho tôi dùng chrome', 'open_app'),
('ngưng chạy spotify', 'close_app'),
('truy cập zingnews.vn', 'open_website'),
('tìm kiếm tài liệu bài tập python', 'find_file'),
('ngưng vscode', 'close_app'),
('tìm kiếm tài liệu ảnh cưới', 'find_file'),
('đóng powerpoint', 'close_app'),
('mở trang stackoverflow.com', 'open_website'),
('mở teams', 'open_app'),
('vào notepad đi', 'open_app'),
('tìm file ảnh cưới', 'find_file'),
('bật tài liệu bài thuyết trình tốt nghiệp', 'find_file'),
('khởi động excel', 'open_app'),
('đóng spotify', 'close_app'),
('đóng ứng dụng vscode', 'close_app'),
('đi tới zingnews.vn', 'open_website'),
('chạy calculator', 'open_app'),
('đóng excel', 'close_app'),
('vào zalo đi', 'open_app'),
('bật tài liệu file kế hoạch', 'find_file'),
('tôi muốn mở calculator', 'open_app'),
('khởi động zalo', 'open_app'),
('khởi động vscode', 'open_app'),
('tìm kiếm tài liệu hợp đồng lao động', 'find_file'),
('mở notepad', 'open_app'),
('bật trang web stackoverflow.com', 'open_website'),
('kết thúc excel', 'close_app'),
('đi vào youtube.com', 'open_website'),
('mở chrome', 'open_app'),
('ngưng vscode', 'close_app'),
('ghé thăm youtube.com', 'open_website'),
('khởi chạy vscode', 'open_app'),
('khởi động paint', 'open_app'),
('truy cập file CV xin việc', 'find_file'),
('khởi chạy zalo', 'open_app'),
('hãy mở teams', 'open_app'),
('bật paint', 'open_app'),
('ghé thăm github.com', 'open_website'),
('cho tôi dùng spotify', 'open_app'),
('mở github.com', 'open_website'),
('tìm file slide bài giảng', 'find_file'),
('bật tài liệu CV xin việc', 'find_file'),
('mở youtube.com', 'open_website'),
('ngưng chạy chrome', 'close_app'),
('bật tài liệu dự toán ngân sách', 'find_file'),
('ngưng chạy notepad', 'close_app'),
('mở trang zingnews.vn', 'open_website'),
('cho tôi dùng zalo', 'open_app'),
('mở calculator', 'open_app'),
('thoát excel', 'close_app'),
('ngưng chạy spotify', 'close_app'),
('khởi động paint', 'open_app'),
('ngưng chạy calculator', 'close_app'),
('tìm file hóa đơn tháng 3', 'find_file'),
('thoát word', 'close_app'),
('vào powerpoint đi', 'open_app'),
('khởi chạy word', 'open_app'),
('khởi chạy excel', 'open_app'),
('vào zalo đi', 'open_app'),
('tắt zalo', 'close_app'),
('lấy file ảnh cưới', 'find_file'),
('mở chat.openai.com', 'open_website'),
('tắt word', 'close_app'),
('truy cập file hóa đơn tháng 3', 'find_file'),
('tìm kiếm tài liệu file kế hoạch', 'find_file'),
('đóng ứng dụng teams', 'close_app'),
('lấy file báo cáo quý 1', 'find_file'),
('tìm file hợp đồng lao động', 'find_file'),
('ghé thăm facebook.com', 'open_website'),
('đi tới google.com', 'open_website'),
('truy cập youtube.com', 'open_website'),
('cho tôi dùng zalo', 'open_app'),
('mở facebook.com', 'open_website'),
('đi tới vnexpress.net', 'open_website'),
('thoát word', 'close_app'),
('mở trang vnexpress.net', 'open_website'),
('ngưng chạy word', 'close_app'),
('mở file kế hoạch', 'find_file'),
('tìm kiếm tài liệu hóa đơn tháng 3', 'find_file'),
('lấy file CV xin việc', 'find_file'),
('bật tài liệu hợp đồng lao động', 'find_file'),
('khởi chạy spotify', 'open_app'),
('truy cập file dự toán ngân sách', 'find_file'),
('hãy mở powerpoint', 'open_app'),
('mở trang zingnews.vn', 'open_website'),
('đóng paint', 'close_app'),
('hãy mở excel', 'open_app'),
('đóng excel', 'close_app'),
('ngưng notepad', 'close_app'),
('tắt spotify', 'close_app'),
('kết thúc teams', 'close_app'),
('ghé thăm vnexpress.net', 'open_website'),
('chạy paint', 'open_app'),
('tắt chrome', 'close_app'),
('thoát teams', 'close_app'),
('ghé thăm zingnews.vn', 'open_website'),
('ngưng chạy zalo', 'close_app'),
('kết thúc calculator', 'close_app'),
('tìm kiếm tài liệu báo cáo quý 1', 'find_file'),
('kết thúc chrome', 'close_app'),
('hãy mở calculator', 'open_app'),
('ngưng chạy powerpoint', 'close_app'),
('mở google.com', 'open_website'),
('truy cập file ảnh cưới', 'find_file'),
('tôi muốn mở vscode', 'open_app'),
('đi tới zingnews.vn', 'open_website'),
('mở file hợp đồng lao động', 'find_file'),
('ngưng paint', 'close_app'),
('tôi muốn mở powerpoint', 'open_app'),
('lấy file slide bài giảng', 'find_file'),
('mở chrome', 'open_app'),
('đóng ứng dụng vscode', 'close_app'),
('đi vào google.com', 'open_website'),
('bật tài liệu hợp đồng lao động', 'find_file'),
('truy cập stackoverflow.com', 'open_website'),
('mở chat.openai.com', 'open_website'),
('truy cập file slide bài giảng', 'find_file'),
('chạy notepad', 'open_app'),
('ngưng chạy paint', 'close_app'),
('hãy mở spotify', 'open_app'),
('mở file ảnh cưới', 'find_file'),
('cho tôi dùng vscode', 'open_app'),
('ngưng chạy vscode', 'close_app'),
('mở hợp đồng lao động', 'find_file'),
('khởi động spotify', 'open_app'),
('kết thúc calculator', 'close_app'),
('mở zingnews.vn', 'open_website'),
('chạy chrome', 'open_app'),
('đóng ứng dụng teams', 'close_app'),
('bật tài liệu bài thuyết trình tốt nghiệp', 'find_file'),
('mở trang github.com', 'open_website'),
('hãy mở chrome', 'open_app'),
('khởi chạy spotify', 'open_app'),
('mở trang chat.openai.com', 'open_website'),
('ngưng calculator', 'close_app'),
('hãy mở vscode', 'open_app'),
('ngưng notepad', 'close_app'),
('cho tôi dùng teams', 'open_app'),
('thoát vscode', 'close_app'),
('ngưng chạy zalo', 'close_app'),
('ngưng chạy notepad', 'close_app'),
('hãy mở word', 'open_app'),
('tôi muốn mở paint', 'open_app'),
('bật tài liệu slide bài giảng', 'find_file'),
('truy cập file báo cáo quý 1', 'find_file'),
('truy cập file hợp đồng lao động', 'find_file'),
('tắt spotify', 'close_app'),
('đóng ứng dụng powerpoint', 'close_app'),
('kết thúc chrome', 'close_app'),
('đóng ứng dụng chrome', 'close_app'),
('bật tài liệu báo cáo quý 1', 'find_file'),
('vào excel đi', 'open_app'),
('hãy mở teams', 'open_app'),
('lấy file ảnh cưới', 'find_file'),
('đi vào stackoverflow.com', 'open_website'),
('mở paint', 'open_app'),
('truy cập file ảnh cưới', 'find_file'),
('đóng notepad', 'close_app'),
('vào notepad đi', 'open_app'),
('tìm file bài tập python', 'find_file'),
('truy cập chat.openai.com', 'open_website'),
('ngưng powerpoint', 'close_app'),
('thoát powerpoint', 'close_app'),
('hãy mở word', 'open_app'),
('đi vào youtube.com', 'open_website'),
('ngưng zalo', 'close_app'),
('tôi muốn mở excel', 'open_app'),
('ngưng chạy powerpoint', 'close_app'),
('ngưng chạy word', 'close_app'),
('đi tới stackoverflow.com', 'open_website'),
('truy cập file file kế hoạch', 'find_file'),
('kết thúc spotify', 'close_app'),
('vào chrome đi', 'open_app'),
('hãy mở notepad', 'open_app'),
('lấy file dự toán ngân sách', 'find_file'),
('mở trang chat.openai.com', 'open_website'),
('truy cập google.com', 'open_website'),
('tìm kiếm tài liệu bài tập python', 'find_file'),
('bật tài liệu CV xin việc', 'find_file'),
('ngưng chạy chrome', 'close_app'),
('bật chrome', 'open_app'),
('chạy vscode', 'open_app'),
('hãy mở vscode', 'open_app'),
('bật trang web vnexpress.net', 'open_website'),
('khởi động vscode', 'open_app'),
('bật calculator', 'open_app'),
('thoát notepad', 'close_app'),
('bật word', 'open_app'),
('cho tôi dùng vscode', 'open_app'),
('mở slide bài giảng', 'find_file'),
('bật paint', 'open_app'),
('bật vscode', 'open_app'),
('mở paint', 'open_app'),
('mở file file kế hoạch', 'find_file'),
('vào vscode đi', 'open_app'),
('kết thúc notepad', 'close_app'),
('hãy mở chrome', 'open_app'),
('đóng ứng dụng calculator', 'close_app'),
('mở hóa đơn tháng 3', 'find_file'),
('lấy file file kế hoạch', 'find_file'),
('tìm kiếm tài liệu slide bài giảng', 'find_file'),
('đóng chrome', 'close_app'),
('bật zalo', 'open_app'),
('tôi muốn mở vscode', 'open_app'),
('khởi chạy zalo', 'open_app'),
('vào excel đi', 'open_app'),
('ngưng spotify', 'close_app'),
('hãy mở paint', 'open_app'),
('tìm kiếm tài liệu CV xin việc', 'find_file'),
('khởi chạy chrome', 'open_app'),
('mở bài tập python', 'find_file'),
('truy cập google.com', 'open_website'),
('mở facebook.com', 'open_website'),
('mở file CV xin việc', 'find_file'),
('vào calculator đi', 'open_app'),
('mở file hợp đồng lao động', 'find_file'),
('hãy mở paint', 'open_app'),
('khởi động excel', 'open_app'),
('cho tôi dùng paint', 'open_app'),
('đóng calculator', 'close_app'),
('kết thúc excel', 'close_app'),
('khởi chạy powerpoint', 'open_app'),
('chạy spotify', 'open_app'),
('mở dự toán ngân sách', 'find_file'),
('mở CV xin việc', 'find_file'),
('mở file báo cáo quý 1', 'find_file'),
('khởi chạy teams', 'open_app'),
('khởi động word', 'open_app'),
('đóng calculator', 'close_app'),
('tắt powerpoint', 'close_app'),
('bật trang web google.com', 'open_website'),
('thoát chrome', 'close_app'),
('bật trang web zingnews.vn', 'open_website'),
('ngưng chrome', 'close_app'),
('bật tài liệu hóa đơn tháng 3', 'find_file'),
('bật tài liệu ảnh cưới', 'find_file'),
('bật vscode', 'open_app'),
('kết thúc notepad', 'close_app'),
('vào chrome đi', 'open_app'),
('bật trang web youtube.com', 'open_website'),
('đóng ứng dụng word', 'close_app'),
('khởi động powerpoint', 'open_app'),
('lấy file slide bài giảng', 'find_file'),
('truy cập vnexpress.net', 'open_website'),
('mở zalo', 'open_app'),
('đi tới chat.openai.com', 'open_website'),
('bật trang web google.com', 'open_website'),
('đóng paint', 'close_app'),
('mở báo cáo quý 1', 'find_file'),
('truy cập facebook.com', 'open_website'),
('vào word đi', 'open_app'),
('thoát calculator', 'close_app'),
('ngưng paint', 'close_app'),
('khởi động spotify', 'open_app'),
('tôi muốn mở notepad', 'open_app'),
('truy cập github.com', 'open_website'),
('truy cập stackoverflow.com', 'open_website'),
('khởi động chrome', 'open_app'),
('vào powerpoint đi', 'open_app'),
('khởi chạy paint', 'open_app'),
('ghé thăm google.com', 'open_website'),
('mở calculator', 'open_app'),
('mở notepad', 'open_app'),
('tìm file bài tập python', 'find_file'),
('bật tài liệu bài tập python', 'find_file'),
('mở excel', 'open_app'),
('chạy zalo', 'open_app'),
('đi vào vnexpress.net', 'open_website'),
('đóng ứng dụng spotify', 'close_app'),
('tôi muốn mở zalo', 'open_app'),
('mở stackoverflow.com', 'open_website'),
('thoát teams', 'close_app'),
('tìm kiếm tài liệu dự toán ngân sách', 'find_file'),
('đóng ứng dụng powerpoint', 'close_app'),
('thoát vscode', 'close_app'),
('bật trang web vnexpress.net', 'open_website'),
('tắt vscode', 'close_app'),
('tôi muốn mở chrome', 'open_app'),
('ghé thăm google.com', 'open_website'),
('tìm file CV xin việc', 'find_file'),
('truy cập youtube.com', 'open_website'),
('mở github.com', 'open_website'),
('bật trang web zingnews.vn', 'open_website'),
('tìm file CV xin việc', 'find_file'),
('mở vnexpress.net', 'open_website'),
('kết thúc powerpoint', 'close_app'),
('chạy notepad', 'open_app'),
('truy cập file bài thuyết trình tốt nghiệp', 'find_file'),
('đóng ứng dụng zalo', 'close_app'),
('đóng ứng dụng excel', 'close_app'),
('ngưng powerpoint', 'close_app'),
('mở youtube.com', 'open_website'),
('đóng zalo', 'close_app'),
('mở file báo cáo quý 1', 'find_file'),
('lấy file CV xin việc', 'find_file'),
('đi vào zingnews.vn', 'open_website'),
('tìm kiếm tài liệu file kế hoạch', 'find_file'),
('đóng spotify', 'close_app'),
('tôi muốn mở chrome', 'open_app'),
('ghé thăm vnexpress.net', 'open_website'),
('tìm file hóa đơn tháng 3', 'find_file'),
('bật tài liệu slide bài giảng', 'find_file'),
('mở zingnews.vn', 'open_website'),
('bật chrome', 'open_app'),
('khởi động notepad', 'open_app'),
('lấy file bài thuyết trình tốt nghiệp', 'find_file'),
('mở zalo', 'open_app'),
('kết thúc word', 'close_app'),
('bật trang web facebook.com', 'open_website'),
('tôi muốn mở word', 'open_app'),
('mở file file kế hoạch', 'find_file'),
('thoát zalo', 'close_app'),
('kết thúc vscode', 'close_app'),
('mở hóa đơn tháng 3', 'find_file'),
('tắt teams', 'close_app'),
('kết thúc word', 'close_app'),
('đi tới youtube.com', 'open_website'),
('đi vào vnexpress.net', 'open_website'),
('đi vào chat.openai.com', 'open_website'),
('truy cập file dự toán ngân sách', 'find_file'),
('tìm file file kế hoạch', 'find_file'),
('bật tài liệu dự toán ngân sách', 'find_file'),
('chạy chrome', 'open_app'),
('thoát paint', 'close_app'),
('truy cập file CV xin việc', 'find_file'),
('tắt zalo', 'close_app'),
('đi tới github.com', 'open_website'),
('mở trang youtube.com', 'open_website'),
('khởi chạy chrome', 'open_app'),
('bật powerpoint', 'open_app'),
('truy cập file file kế hoạch', 'find_file'),
('khởi chạy paint', 'open_app'),
('bật trang web github.com', 'open_website'),
('mở ảnh cưới', 'find_file'),
('bật trang web chat.openai.com', 'open_website'),
('cho tôi dùng notepad', 'open_app'),
('lấy file hợp đồng lao động', 'find_file'),
('khởi động chrome', 'open_app'),
('bật calculator', 'open_app'),
('truy cập file bài thuyết trình tốt nghiệp', 'find_file'),
('đóng vscode', 'close_app'),
('đóng ứng dụng notepad', 'close_app'),
('ghé thăm zingnews.vn', 'open_website'),
('đi tới chat.openai.com', 'open_website'),
('đóng ứng dụng paint', 'close_app'),
('chạy excel', 'open_app'),
('ngưng calculator', 'close_app'),
('thoát powerpoint', 'close_app'),
('bật spotify', 'open_app'),
('khởi chạy vscode', 'open_app'),
('bật teams', 'open_app'),
('tắt paint', 'close_app'),
('đóng chrome', 'close_app'),
('lấy file hóa đơn tháng 3', 'find_file'),
('ghé thăm chat.openai.com', 'open_website'),
('ghé thăm youtube.com', 'open_website'),
('lấy file file kế hoạch', 'find_file'),
('ngưng chrome', 'close_app'),
('truy cập chat.openai.com', 'open_website'),
('đi tới youtube.com', 'open_website'),
('lấy file báo cáo quý 1', 'find_file'),
('tôi muốn mở word', 'open_app'),
('chạy powerpoint', 'open_app'),
('tìm file ảnh cưới', 'find_file'),
('mở file slide bài giảng', 'find_file'),
('cho tôi dùng word', 'open_app'),
('mở vnexpress.net', 'open_website'),
('tôi muốn mở powerpoint', 'open_app'),
('tìm file báo cáo quý 1', 'find_file'),
('đóng word', 'close_app'),
('tôi muốn mở zalo', 'open_app'),
('mở trang stackoverflow.com', 'open_website'),
('bật trang web youtube.com', 'open_website'),
('mở bài thuyết trình tốt nghiệp', 'find_file'),
('mở bài tập python', 'find_file'),
('ghé thăm chat.openai.com', 'open_website'),
('vào spotify đi', 'open_app'),
('kết thúc zalo', 'close_app'),
('mở word', 'open_app'),
('tìm file dự toán ngân sách', 'find_file'),
('mở file bài thuyết trình tốt nghiệp', 'find_file'),
('vào calculator đi', 'open_app'),
('đóng ứng dụng chrome', 'close_app'),
('tắt excel', 'close_app'),
('chạy excel', 'open_app'),
('thoát calculator', 'close_app'),
('ngưng chạy excel', 'close_app'),
('mở file CV xin việc', 'find_file'),
('cho tôi dùng notepad', 'open_app'),
('bật word', 'open_app'),
('kết thúc paint', 'close_app'),
('tôi muốn mở paint', 'open_app'),
('tìm file file kế hoạch', 'find_file'),
('khởi động powerpoint', 'open_app'),
('mở trang github.com', 'open_website'),
('đóng ứng dụng spotify', 'close_app'),
('lấy file hóa đơn tháng 3', 'find_file'),
('truy cập zingnews.vn', 'open_website'),
('khởi chạy word', 'open_app'),
('lấy file bài tập python', 'find_file'),
('khởi động calculator', 'open_app'),
('bật trang web chat.openai.com', 'open_website'),
('tìm kiếm tài liệu ảnh cưới', 'find_file'),
('cho tôi dùng excel', 'open_app'),
('thoát spotify', 'close_app'),
('ghé thăm github.com', 'open_website'),
('tôi muốn mở calculator', 'open_app'),
('ngưng zalo', 'close_app'),
('chạy teams', 'open_app'),
('đóng teams', 'close_app'),
('mở trang google.com', 'open_website'),
('tìm kiếm tài liệu báo cáo quý 1', 'find_file'),
('ngưng chạy teams', 'close_app'),
('bật notepad', 'open_app'),
('đóng powerpoint', 'close_app'),
('tắt calculator', 'close_app'),
('vào teams đi', 'open_app'),
('bật excel', 'open_app'),
('cho tôi dùng calculator', 'open_app'),
('bật trang web github.com', 'open_website'),
('ngưng excel', 'close_app'),
('kết thúc powerpoint', 'close_app'),
('mở trang facebook.com', 'open_website'),
('ngưng word', 'close_app'),
('mở ảnh cưới', 'find_file'),
('tắt calculator', 'close_app'),
('vào word đi', 'open_app'),
('đi tới stackoverflow.com', 'open_website'),
('cho tôi dùng calculator', 'open_app'),
('chạy calculator', 'open_app'),
('hãy mở excel', 'open_app'),
('thoát chrome', 'close_app'),
('ngưng chạy excel', 'close_app'),
('mở hợp đồng lao động', 'find_file'),
('đi vào zingnews.vn', 'open_website'),
('truy cập file hóa đơn tháng 3', 'find_file'),
('bật powerpoint', 'open_app'),
('truy cập file bài tập python', 'find_file'),
('mở trang facebook.com', 'open_website'),
('mở file dự toán ngân sách', 'find_file'),
('chạy word', 'open_app'),
('mở dự toán ngân sách', 'find_file'),
('ngưng teams', 'close_app'),
('khởi động teams', 'open_app'),
('bật spotify', 'open_app'),
('chạy paint', 'open_app'),
('tìm kiếm tài liệu dự toán ngân sách', 'find_file'),
('đi tới vnexpress.net', 'open_website'),
('mở báo cáo quý 1', 'find_file'),
('vào spotify đi', 'open_app'),
('ngưng teams', 'close_app'),
('truy cập file slide bài giảng', 'find_file'),
('mở vscode', 'open_app'),
('lấy file dự toán ngân sách', 'find_file'),
('hãy mở calculator', 'open_app'),
('cho tôi dùng powerpoint', 'open_app'),
('đóng ứng dụng calculator', 'close_app'),
('đóng ứng dụng notepad', 'close_app'),
('tôi muốn mở teams', 'open_app'),
('tắt powerpoint', 'close_app'),
('đi vào chat.openai.com', 'open_website'),
('mở file bài thuyết trình tốt nghiệp', 'find_file'),
('hãy mở spotify', 'open_app'),
('bật zalo', 'open_app'),
('mở file kế hoạch', 'find_file'),
('vào vscode đi', 'open_app'),
('mở google.com', 'open_website'),
('cho tôi dùng word', 'open_app'),
('đóng notepad', 'close_app'),
('cho tôi dùng spotify', 'open_app'),
('tìm file bài thuyết trình tốt nghiệp', 'find_file'),
('mở file bài tập python', 'find_file'),
('truy cập facebook.com', 'open_website'),
('tắt excel', 'close_app'),
('mở vscode', 'open_app'),
('bật teams', 'open_app'),
('mở file slide bài giảng', 'find_file'),
('bật tài liệu file kế hoạch', 'find_file'),
('chạy vscode', 'open_app'),
('hãy mở zalo', 'open_app'),
('cho tôi dùng chrome', 'open_app'),
('tắt notepad', 'close_app'),
('đi vào stackoverflow.com', 'open_website'),
('ghé thăm facebook.com', 'open_website'),
('hãy mở powerpoint', 'open_app'),
('tìm kiếm tài liệu bài thuyết trình tốt nghiệp', 'find_file'),
('tôi muốn mở spotify', 'open_app'),
('mở powerpoint', 'open_app'),
('khởi động notepad', 'open_app'),
('tắt notepad', 'close_app'),
('ngưng chạy paint', 'close_app'),
('mở spotify', 'open_app'),
('cho tôi dùng excel', 'open_app'),
('khởi động teams', 'open_app'),
('cho tôi dùng powerpoint', 'open_app'),
('vào teams đi', 'open_app'),
('mở trang vnexpress.net', 'open_website'),
('đi vào github.com', 'open_website'),
('tôi muốn mở notepad', 'open_app'),
('đóng teams', 'close_app'),
('mở file bài tập python', 'find_file'),
('bật tài liệu hóa đơn tháng 3', 'find_file'),
('khởi chạy excel', 'open_app'),
('lấy file bài tập python', 'find_file'),
('mở file hóa đơn tháng 3', 'find_file'),
('truy cập file báo cáo quý 1', 'find_file'),
('truy cập github.com', 'open_website'),
('tôi muốn mở spotify', 'open_app'),
('vào paint đi', 'open_app'),
('ngưng word', 'close_app'),
('tắt word', 'close_app'),
('ngưng chạy teams', 'close_app'),
('lấy file hợp đồng lao động', 'find_file'),
('khởi động zalo', 'open_app'),
('ngưng chạy calculator', 'close_app'),
('mở bài thuyết trình tốt nghiệp', 'find_file'),
('thoát excel', 'close_app'),
('tìm kiếm tài liệu CV xin việc', 'find_file'),
('khởi chạy calculator', 'open_app'),
('mở file dự toán ngân sách', 'find_file'),
('khởi chạy notepad', 'open_app'),
('mở teams', 'open_app'),
('đóng vscode', 'close_app'),
('ngưng spotify', 'close_app'),
('tìm kiếm tài liệu hóa đơn tháng 3', 'find_file'),
('đi tới google.com', 'open_website'),
('chạy spotify', 'open_app'),
('lấy file bài thuyết trình tốt nghiệp', 'find_file'),
('tôi muốn mở teams', 'open_app'),
('bật tài liệu bài tập python', 'find_file'),
('bật notepad', 'open_app'),
('bật trang web stackoverflow.com', 'open_website'),
('tắt vscode', 'close_app'),
('đóng word', 'close_app'),
('mở trang google.com', 'open_website'),
('đi vào github.com', 'open_website'),
('khởi chạy teams', 'open_app'),
('ngưng excel', 'close_app'),
('đi tới facebook.com', 'open_website'),
('kết thúc paint', 'close_app'),
('mở slide bài giảng', 'find_file'),
('đóng ứng dụng word', 'close_app'),
('chạy teams', 'open_app'),
('thoát spotify', 'close_app'),
('tìm file hợp đồng lao động', 'find_file'),
('khởi chạy calculator', 'open_app'),
('truy cập file bài tập python', 'find_file'),
('tìm kiếm tài liệu bài thuyết trình tốt nghiệp', 'find_file'),
('đóng ứng dụng paint', 'close_app'),
('đi vào facebook.com', 'open_website'),
('chạy word', 'open_app'),
('mở file ảnh cưới', 'find_file'),
('truy cập file hợp đồng lao động', 'find_file'),
('mở trang youtube.com', 'open_website'),
('khởi động calculator', 'open_app'),
('tắt chrome', 'close_app'),
('hãy mở zalo', 'open_app'),
('kết thúc zalo', 'close_app'),
('tôi muốn mở excel', 'open_app'),
('bật tài liệu ảnh cưới', 'find_file'),
('kết thúc spotify', 'close_app'),
('đi vào google.com', 'open_website'),
('cho tôi dùng paint', 'open_app'),
('thoát notepad', 'close_app'),
('mở CV xin việc', 'find_file'),
('tắt paint', 'close_app'),
('bật tài liệu báo cáo quý 1', 'find_file'),
('chạy zalo', 'open_app'),
('tắt teams', 'close_app'),
('mở stackoverflow.com', 'open_website'),
('mở excel', 'open_app'),
('bật trang web facebook.com', 'open_website'),
('tìm file báo cáo quý 1', 'find_file'),
('đóng ứng dụng excel', 'close_app'),
('khởi chạy powerpoint', 'open_app'),
('tìm kiếm tài liệu slide bài giảng', 'find_file'),
('mở spotify', 'open_app'),
('tìm file bài thuyết trình tốt nghiệp', 'find_file'),
('bật excel', 'open_app'),
('đi vào facebook.com', 'open_website'),
('kết thúc vscode', 'close_app'),
('ghé thăm stackoverflow.com', 'open_website'),
('đóng zalo', 'close_app'),
('cho tôi dùng teams', 'open_app'),
('khởi động word', 'open_app'),
('tìm file dự toán ngân sách', 'find_file'),
('chạy powerpoint', 'open_app'),
('mở word', 'open_app'),
('thoát paint', 'close_app'),
('ghé thăm stackoverflow.com', 'open_website'),
('truy cập vnexpress.net', 'open_website'),
('thoát zalo', 'close_app'),
('tìm file slide bài giảng', 'find_file'),
('đi tới github.com', 'open_website'),
('đi tới facebook.com', 'open_website'),
('mở file hóa đơn tháng 3', 'find_file'),
("hiển thị thêm", "show_more"),
    ("xem thêm", "show_more"),
    ("hiển thị kết quả tiếp theo", "show_more"),
    ("xem thêm thông tin", "show_more"),
    ("hiển thị danh sách tiếp theo", "show_more"),
    ("xem các mục khác", "show_more"),
    ("hiển thị thêm dữ liệu", "show_more"),
    ("xem thêm kết quả tìm kiếm", "show_more"),
    ("hiển thị các mục tiếp theo", "show_more"),
    ("xem thêm nội dung", "show_more"),
    ("hiển thị tiếp", "show_more"),
    ("xem thêm danh sách", "show_more"),
    ("hiển thị các kết quả khác", "show_more"),
    ("xem thêm chi tiết", "show_more"),
    ("hiển thị thêm thông tin", "show_more"),
    ("xem các mục tiếp theo", "show_more"),
    ("hiển thị thêm kết quả", "show_more"),
    ("xem thêm dữ liệu", "show_more"),
    ("hiển thị danh sách khác", "show_more"),
    ("xem tiếp theo", "show_more"),
    ("hiển thị thêm mục", "show_more"),
    ("xem thêm kết quả khác", "show_more"),
    ("hiển thị các nội dung tiếp theo", "show_more"),
    ("xem thêm thông tin khác", "show_more"),
    ("hiển thị tiếp theo", "show_more"),
    ("xem các kết quả tiếp theo", "show_more"),
    ("hiển thị thêm danh sách", "show_more"),
    ("xem thêm mục khác", "show_more"),
    ("hiển thị các mục bổ sung", "show_more"),
    ("xem thêm nội dung khác", "show_more"),
    ("hiển thị thêm chi tiết", "show_more"),
    ("xem các mục bổ sung", "show_more"),
    ("hiển thị kết quả bổ sung", "show_more"),
    ("xem thêm danh sách khác", "show_more"),
    ("hiển thị thêm nội dung", "show_more"),
    ("xem các thông tin tiếp theo", "show_more"),
    ("hiển thị danh sách bổ sung", "show_more"),
    ("xem thêm kết quả bổ sung", "show_more"),
    ("hiển thị các mục còn lại", "show_more"),
    ("xem thêm các mục", "show_more"),
    ("hiển thị thêm các mục", "show_more"),
    ("xem các nội dung khác", "show_more"),
    ("hiển thị thêm kết quả tìm kiếm", "show_more"),
    ("xem thêm các kết quả", "show_more"),
    ("hiển thị các danh sách tiếp theo", "show_more"),
    ("xem thêm thông tin bổ sung", "show_more"),
    ("hiển thị thêm các thông tin", "show_more"),
    ("xem các mục còn lại", "show_more"),
    ("hiển thị thêm", "show_more"),
]