# train_intent_data.py
TRAIN_DATA = [
    # open_app (60 ví dụ)
    ("mở notepad", "open_app"),
    ("mở chrome", "open_app"),
    ("mở excel", "open_app"),
    ("khởi động word", "open_app"),
    ("mở trình duyệt", "open_app"),
    ("mở ứng dụng paint", "open_app"),
    ("chạy powerpoint", "open_app"),
    ("mở ứng dụng máy tính", "open_app"),
    ("hãy mở chrome", "open_app"),
    ("khởi chạy vlc", "open_app"),
    ("mở phần mềm photoshop", "open_app"),
    ("mở trình phát nhạc", "open_app"),
    ("bật word", "open_app"),
    ("mở ứng dụng skype", "open_app"),
    ("khởi động trình duyệt firefox", "open_app"),
    ("mở phần mềm calculator", "open_app"),
    ("chạy ứng dụng teams", "open_app"),
    ("mở trình chỉnh sửa ảnh", "open_app"),
    ("hãy khởi động excel", "open_app"),
    ("mở ứng dụng outlook", "open_app"),
    ("bật notepad", "open_app"),
    ("mở phần mềm zoom", "open_app"),
    ("khởi chạy powerpoint", "open_app"),
    ("mở ứng dụng telegram", "open_app"),
    ("chạy trình duyệt edge", "open_app"),
    ("mở phần mềm code visual studio", "open_app"),
    ("hãy mở paint", "open_app"),
    ("mở ứng dụng wordpad", "open_app"),
    ("bật trình phát video", "open_app"),
    ("mở ứng dụng onenote", "open_app"),
    ("khởi động photoshop", "open_app"),
    ("mở trình quản lý tệp", "open_app"),
    ("chạy ứng dụng discord", "open_app"),
    ("mở phần mềm gimp", "open_app"),
    ("hãy khởi chạy chrome", "open_app"),
    ("mở ứng dụng slack", "open_app"),
    ("bật powerpoint", "open_app"),
    ("mở trình duyệt opera", "open_app"),
    ("khởi động ứng dụng excel", "open_app"),
    ("mở phần mềm audacity", "open_app"),
    ("chạy trình chỉnh sửa video", "open_app"),
    ("mở ứng dụng trello", "open_app"),
    ("hãy mở skype", "open_app"),
    ("mở trình phát mp3", "open_app"),
    ("bật ứng dụng calculator", "open_app"),
    ("mở phần mềm obs", "open_app"),
    ("khởi chạy word", "open_app"),
    ("mở ứng dụng viber", "open_app"),
    ("chạy trình duyệt safari", "open_app"),
    ("mở phần mềm canva", "open_app"),
    ("hãy khởi động notepad", "open_app"),
    ("mở ứng dụng notepad", "open_app"),
    ("chạy phần mềm word", "open_app"),
    ("bật trình duyệt firefox", "open_app"),
    ("khởi chạy ứng dụng excel", "open_app"),
    ("mở chương trình vlc", "open_app"),
    ("hãy bật powerpoint", "open_app"),
    ("mở ứng dụng teams", "open_app"),
    ("khởi động trình chỉnh sửa ảnh", "open_app"),
    ("mở phần mềm skype", "open_app"),
    
    # find_file (50 ví dụ)
    ("tìm file Báo cáo.docx", "find_file"),
    ("tìm file excel trong ổ D", "find_file"),
    ("tìm ảnh trong thư mục Pictures", "find_file"),
    ("mở file Báo cáo tháng 10 trong ổ D bằng excel", "find_file"),
    ("tìm video trong ổ E", "find_file"),
    ("tìm tài liệu hợp đồng.pdf", "find_file"),
    ("tìm file word trong ổ C", "find_file"),
    ("tìm ảnh chụp hôm qua", "find_file"),
    ("tìm file Báo cáo.docx trong ổ D", "find_file"),
    ("tìm file powerpoint trong thư mục Tài liệu", "find_file"),
    ("tìm kiếm tài liệu Báo cáo trên ổ D", "find_file"),
    ("tìm file pdf trong thư mục Downloads", "find_file"),
    ("tìm ảnh vacation.jpg", "find_file"),
    ("tìm file excel trên Desktop", "find_file"),
    ("tìm tài liệu kế hoạch.docx trong ổ F", "find_file"),
    ("tìm video hội nghị.mp4", "find_file"),
    ("tìm file word tên Báo cáo hàng tháng", "find_file"),
    ("tìm ảnh trong ổ E", "find_file"),
    ("tìm file presentation.pptx", "find_file"),
    ("tìm tài liệu hợp đồng trong thư mục Công việc", "find_file"),
    ("tìm file Báo cáo.docx trên ổ C", "find_file"),
    ("tìm video gia đình trong ổ D", "find_file"),
    ("tìm file pdf tên Hướng dẫn", "find_file"),
    ("tìm ảnh chụp tiệc sinh nhật", "find_file"),
    ("tìm file excel trong thư mục Kế toán", "find_file"),
    ("tìm tài liệu word trên ổ E", "find_file"),
    ("tìm file powerpoint trong ổ C", "find_file"),
    ("tìm video trong thư mục Media", "find_file"),
    ("tìm file Báo cáo hàng quý.docx", "find_file"),
    ("tìm ảnh trong thư mục Ảnh cá nhân", "find_file"),
    ("tìm file pdf trong ổ D", "find_file"),
    ("tìm tài liệu kế hoạch trong thư mục Dự án", "find_file"),
    ("tìm file excel tên Doanh thu", "find_file"),
    ("tìm video quảng cáo.mp4", "find_file"),
    ("tìm file word trong thư mục Tài liệu", "find_file"),
    ("tìm ảnh chụp du lịch", "find_file"),
    ("tìm file powerpoint tên Trình bày", "find_file"),
    ("tìm tài liệu hợp đồng.pdf trên Desktop", "find_file"),
    ("tìm file Báo cáo.docx trong thư mục Báo cáo", "find_file"),
    ("tìm video trong ổ F", "find_file"),
    ("tìm file excel trong ổ E", "find_file"),
    ("tìm ảnh trong thư mục Hình ảnh", "find_file"),
    ("tìm file word tên Hợp đồng", "find_file"),
    ("tìm file pdf trong thư mục Tài liệu", "find_file"),
    ("tìm video hội thảo trong ổ D", "find_file"),
    ("tìm file powerpoint trong thư mục Trình bày", "find_file"),
    ("tìm ảnh chụp sự kiện", "find_file"),
    ("tìm file excel trên ổ C", "find_file"),
    ("tìm tài liệu Báo cáo trong ổ E", "find_file"),
    ("tìm file Báo cáo.docx", "find_file"),
    
    # open_website (50 ví dụ)
    ("vào google", "open_website"),
    ("tìm bài hát Yesterday", "open_website"),
    ("vào youtube", "open_website"),
    ("mở facebook bằng chrome", "open_website"),
    ("truy cập trang vnexpress", "open_website"),
    ("mở website google.com", "open_website"),
    ("vào trang báo thanh niên", "open_website"),
    ("tìm video trên youtube", "open_website"),
    ("mở trang web zalo", "open_website"),
    ("truy cập shopee", "open_website"),
    ("mở trang tiki", "open_website"),
    ("vào trang báo dân trí", "open_website"),
    ("mở website amazon", "open_website"),
    ("tìm bài viết trên google", "open_website"),
    ("vào trang linkedin", "open_website"),
    ("mở trang web instagram", "open_website"),
    ("truy cập trang tuoitre", "open_website"),
    ("mở website netflix", "open_website"),
    ("vào trang báo pháp luật", "open_website"),
    ("tìm thông tin trên google", "open_website"),
    ("mở trang web twitter", "open_website"),
    ("vào trang shopee.vn", "open_website"),
    ("mở website spotify", "open_website"),
    ("truy cập trang báo 24h", "open_website"),
    ("mở trang web lazada", "open_website"),
    ("vào trang pinterest", "open_website"),
    ("tìm video trên vimeo", "open_website"),
    ("mở website bbc", "open_website"),
    ("vào trang báo vietnamnet", "open_website"),
    ("mở trang web tiktok", "open_website"),
    ("truy cập trang thegioididong", "open_website"),
    ("mở website reddit", "open_website"),
    ("vào trang báo zing", "open_website"),
    ("tìm bài hát trên google", "open_website"),
    ("mở trang web medium", "open_website"),
    ("vào trang báo tuổi trẻ", "open_website"),
    ("mở website fpt shop", "open_website"),
    ("truy cập trang báo dân việt", "open_website"),
    ("mở trang web soundcloud", "open_website"),
    ("vào trang báo thể thao", "open_website"),
    ("tìm tin tức trên google", "open_website"),
    ("mở website github", "open_website"),
    ("vào trang báo công an", "open_website"),
    ("mở trang web dropbox", "open_website"),
    ("truy cập trang báo vov", "open_website"),
    ("mở website drive.google.com", "open_website"),
    ("vào trang báo người lao động", "open_website"),
    ("tìm nội dung trên youtube", "open_website"),
    ("mở trang web notion", "open_website"),
    ("vào google", "open_website"),
    
    # close_app (60 ví dụ)
    ("đóng chrome", "close_app"),
    ("đóng notepad", "close_app"),
    ("tắt trình duyệt", "close_app"),
    ("đóng ứng dụng word", "close_app"),
    ("tắt excel", "close_app"),
    ("đóng chương trình paint", "close_app"),
    ("tắt powerpoint", "close_app"),
    ("đóng ứng dụng máy tính", "close_app"),
    ("tắt trình phát nhạc", "close_app"),
    ("đóng phần mềm vlc", "close_app"),
    ("thoát chrome", "close_app"),
    ("đóng ứng dụng skype", "close_app"),
    ("tắt firefox", "close_app"),
    ("đóng chương trình calculator", "close_app"),
    ("tắt teams", "close_app"),
    ("đóng trình chỉnh sửa ảnh", "close_app"),
    ("thoát excel", "close_app"),
    ("đóng ứng dụng outlook", "close_app"),
    ("tắt notepad", "close_app"),
    ("đóng phần mềm zoom", "close_app"),
    ("tắt powerpoint", "close_app"),
    ("đóng ứng dụng telegram", "close_app"),
    ("thoát edge", "close_app"),
    ("đóng chương trình visual studio", "close_app"),
    ("tắt paint", "close_app"),
    ("đóng ứng dụng wordpad", "close_app"),
    ("tắt trình phát video", "close_app"),
    ("đóng ứng dụng onenote", "close_app"),
    ("thoát photoshop", "close_app"),
    ("đóng trình quản lý tệp", "close_app"),
    ("tắt discord", "close_app"),
    ("đóng phần mềm gimp", "close_app"),
    ("thoát chrome", "close_app"),
    ("đóng ứng dụng slack", "close_app"),
    ("tắt powerpoint", "close_app"),
    ("đóng trình duyệt opera", "close_app"),
    ("thoát excel", "close_app"),
    ("đóng phần mềm audacity", "close_app"),
    ("tắt trình chỉnh sửa video", "close_app"),
    ("đóng ứng dụng trello", "close_app"),
    ("thoát skype", "close_app"),
    ("đóng trình phát mp3", "close_app"),
    ("tắt ứng dụng calculator", "close_app"),
    ("đóng phần mềm obs", "close_app"),
    ("thoát word", "close_app"),
    ("đóng ứng dụng viber", "close_app"),
    ("tắt trình duyệt safari", "close_app"),
    ("đóng phần mềm canva", "close_app"),
    ("tắt chrome", "close_app"),
    ("thoát notepad", "close_app"),
    ("kết thúc chrome", "close_app"),
    ("tắt ứng dụng excel", "close_app"),
    ("đóng trình duyệt firefox", "close_app"),
    ("thoát powerpoint", "close_app"),
    ("tắt chương trình vlc", "close_app"),
    ("đóng ứng dụng teams", "close_app"),
    ("kết thúc trình phát nhạc", "close_app"),
    ("tắt phần mềm skype", "close_app"),
    ("đóng chương trình paint", "close_app"),
    
    # show_more (50 ví dụ)
    ("hiển thị thêm", "show_more"),
    ("xem thêm", "show_more"),
    ("hiển thị kết quả tiếp theo", "show_more"),
    ("xem thêm thông tin", "show_more"),
    ("hiển thị danh sách tiếp theo", "show_more"),
    ("xem các mục khác", "show_more"),
    ("hiển thị thêm dữ liệu", "show_more"),
    ("xem thêm kết quả tìm kiếm", "show_more"),
    ("hiển thị các mục tiếp theo", "show_more"),
    ("xem thêm nội dung", "show_more"),
    ("hiển thị tiếp", "show_more"),
    ("xem thêm danh sách", "show_more"),
    ("hiển thị các kết quả khác", "show_more"),
    ("xem thêm chi tiết", "show_more"),
    ("hiển thị thêm thông tin", "show_more"),
    ("xem các mục tiếp theo", "show_more"),
    ("hiển thị thêm kết quả", "show_more"),
    ("xem thêm dữ liệu", "show_more"),
    ("hiển thị danh sách khác", "show_more"),
    ("xem tiếp theo", "show_more"),
    ("hiển thị thêm mục", "show_more"),
    ("xem thêm kết quả khác", "show_more"),
    ("hiển thị các nội dung tiếp theo", "show_more"),
    ("xem thêm thông tin khác", "show_more"),
    ("hiển thị tiếp theo", "show_more"),
    ("xem các kết quả tiếp theo", "show_more"),
    ("hiển thị thêm danh sách", "show_more"),
    ("xem thêm mục khác", "show_more"),
    ("hiển thị các mục bổ sung", "show_more"),
    ("xem thêm nội dung khác", "show_more"),
    ("hiển thị thêm chi tiết", "show_more"),
    ("xem các mục bổ sung", "show_more"),
    ("hiển thị kết quả bổ sung", "show_more"),
    ("xem thêm danh sách khác", "show_more"),
    ("hiển thị thêm nội dung", "show_more"),
    ("xem các thông tin tiếp theo", "show_more"),
    ("hiển thị danh sách bổ sung", "show_more"),
    ("xem thêm kết quả bổ sung", "show_more"),
    ("hiển thị các mục còn lại", "show_more"),
    ("xem thêm các mục", "show_more"),
    ("hiển thị thêm các mục", "show_more"),
    ("xem các nội dung khác", "show_more"),
    ("hiển thị thêm kết quả tìm kiếm", "show_more"),
    ("xem thêm các kết quả", "show_more"),
    ("hiển thị các danh sách tiếp theo", "show_more"),
    ("xem thêm thông tin bổ sung", "show_more"),
    ("hiển thị thêm các thông tin", "show_more"),
    ("xem các mục còn lại", "show_more"),
    ("hiển thị thêm", "show_more"),
]