TRAIN_DATA = [
    ('hãy truy cập thư mục Tài liệu', {'entities': [(15, 32, 'PATH')]}),
    ('đi tới thư mục Downloads', {'entities': [(9, 28, 'PATH')]}),
    ('kiểm tra trong ổ D', {'entities': [(13, 19, 'PATH')]}),
    ('lưu file vào thư mục Học tập', {'entities': [(14, 33, 'PATH')]}),
    ('mở file trong thư mục D:\\Báo cáo', {'entities': [(8, 34, 'PATH')]}),
    ('mở ứng dụng Word', {'entities': [(13, 17, 'APP')]}),
    ('chạy Excel', {'entities': [(6, 11, 'APP')]}),
    ('mở Notepad', {'entities': [(4, 11, 'APP')]}),
    ('khởi động PowerPoint', {'entities': [(12, 22, 'APP')]}),
    ('dùng trình phát VLC', {'entities': [(16, 19, 'APP')]}),
    ('mở file báo cáo.docx', {'entities': [(9, 23, 'FILE')]}),
    ('mở file update.xlsx bằng Excel', {'entities': [(9, 21, 'FILE'), (28, 33, 'APP')]}),
    ('tìm file presentation.pptx trong thư mục Tài liệu', {'entities': [(10, 30, 'FILE'), (37, 56, 'PATH')]}),
    ('mở report_final.pdf', {'entities': [(4, 21, 'FILE')]}),
    ('xem hình ảnh data.png', {'entities': [(14, 22, 'FILE')]}),
    ('tìm bài hát Yesterday trên Youtube', {'entities': [(10, 19, 'QUERY'), (26, 33, 'APP')]}),
    ('xem video Tháng Tư là lời nói dối trên Youtube', {'entities': [(10, 39, 'QUERY'), (46, 53, 'APP')]}),
    ('nghe nhạc Despacito trên Spotify', {'entities': [(10, 19, 'QUERY'), (26, 34, 'APP')]}),
    ('tìm kiếm bài hát Hello', {'entities': [(16, 21, 'QUERY')]}),
    ('phát video Hạ Còn Vương Nắng', {'entities': [(11, 30, 'QUERY')]}),
    ('mở file Báo cáo.docx trong ổ D', {'entities': [(9, 23, 'FILE'), (30, 35, 'PATH')]}),
    ('mở file report.xlsx trong thư mục Downloads bằng Excel', {'entities': [(9, 21, 'FILE'), (28, 48, 'PATH'), (55, 60, 'APP')]}),
    ('tìm video Faded trên Youtube và mở bằng VLC', {'entities': [(10, 15, 'QUERY'), (22, 29, 'APP'), (40, 43, 'APP')]}),
]
